### ISSUE TITLE
Misuse NES in PROGENy zscores

### ISSUE THREAD

**Issue by jperales** [saezlab/transcriptutorial#11]
https://github.com/saezlab/transcriptutorial/blob/81c76439d0c2ad7c451aefab332029ffe1034a03/scripts/03_Pathway_activity_with_Progeny.Rmd#L132-L160

Reference above. I think using NES for PROGENy z-scores is not correct. If so, Should we correct this?
Thanks

Javier

**Comment by adugourd** [comment]
Ah yes this is confusing. Actually it is a normalised enrichment score. Nes and z-score are the same for weighted mean enrichment strategy, which is what is done in progeny.

I'm not sure how to make it less confusing though.
