### ISSUE TITLE
Error in sample_resolution_carnival.R obtaining tfList with larger ncol data

### ISSUE THREAD

**Issue by IvanEllson** [saezlab/transcriptutorial#12]
Hello, thank you for the tutorial.
In the _06_analysis_CARNIVAL_results_ tutorial you use a _carnival sample resolution_ object generated from the _sample_resolution_carnival.R_ script (I think maybe you should explain in the tutorial where it comes from in order to understand it better)

I think I found an error in the code of this _sample_resolution_carnival.R_ script, line 22:

`tfList = generateTFList(tf_activities_carnival, top=50, access_idx = 1:nrow(tf_activities_carnival))`

where it should be `access_idx = 1:ncol(tf_activities_carnival)`

I found that error becouse my data set have more samples than TFs and my resulting tfList was giving me a list with missing samples.
I hope it helps.
Thank you.

**Comment by rosherbal** [comment]
Dear @IvanEllson,

Thanks for your feedback! I have fixed the reported bug and added a note in the main notebook referring the sample resolution scripts :)

All the best,

Rosa
