### ISSUE TITLE
Does this method also apply to microarray data?

### ISSUE THREAD

**Issue by sqianglan** [saezlab/transcriptutorial#14]
Thanks for the nice tutorial. Really enjoy it with my RNAseq data. Just wonder, does it work with microarray data as well?

**Comment by adugourd** [comment]
Thanks for your kind comment, very happy to hear it was usefull !

Indeed, it can be used almost entirelly seamlessly for micro-array data. The only potential difference might be the way you filter lowly expressed genes in the first part, but everything else should work in the same manner, starting at the VSN normalisation.

Cheers,

Aurelien

**Comment by sqianglan** [comment]
Great. I will try.

**Comment by adugourd** [comment]
@sqianglan did this work out ?
