### ISSUE TITLE
Results of TF activites

### ISSUE THREAD

**Issue by Semple-bio** [saezlab/transcriptutorial#16]
In part "04_TranscriptionFactor_activity_with_Dorothea", how are the TF activities calculated?
Or, what does it mean if a TF has a high or low NES? Wouldn't it mean that the associated genes are mostly changed in that direction?
When I plot (volcano_nice) my 3 topmost TFs' regulons, 2 of them has almost exclusively downregulated genes, and from the bottom-most 3 TFs' regulons, one has almost exclusively upregulated genes.

Also in the tutorial dataset the downregulated TF's (ZNF263) regulon has much more upregulated genes than downregulated.

**Comment by rosherbal** [comment]
Hi @Semple-bio,
We calculate the TF activities with DOROTHEA. Check the [bioconductor](https://bioconductor.org/packages/release/data/experiment/html/dorothea.html) package or the [github site](https://github.com/saezlab/dorothea) to learn more about it.

**Comment by Semple-bio** [comment]
I did so. But I'm not sure how to interpret these results when I get conflicting results as written above.

**Comment by gabora** [comment]
Hi, 
jumping in the conversation;) 
Please check the mode of action! The activity is calculated based on the expression of the target genes, but also taking into account if the TF up or downregulates the expression!

**Comment by Semple-bio** [comment]
Thanks, now it starts to make sense :)
