### ISSUE TITLE
Shared interactions figure

### ISSUE THREAD

**Issue by Semple-bio** [saezlab/transcriptutorial#20]
Good day.

Could someone elaborate on the final figure of the workflow? I made the shared interactions figure separately for the WTs (as in the pipeline) and for the KO samples. There are a lot of seemingly important differences.
What do these snippets of the networks represent?
Is it simply higher expression of each members of them, or are these higher expression for the mother nodes and then depending on the interaction type, higher or lower expression of the child nodes? Or something entirely different?

**Comment by rosherbal** [comment]
Hi, 
The last figure represent the nodes and interactions that appear in all samples. That is, all the interactions shared for all the samples.
