### ISSUE TITLE
Error with top(100) in tutorial#3

### ISSUE THREAD

**Issue by asumann** [saezlab/transcriptutorial#22]
Hi,

Many thanks for the tutorial!!

I am getting this error with top=100:
```
PathwayActivity_zscore <- progeny(ttop_KOvsWT_matrix, 
                                  scale=TRUE, organism="Human", top = 100, perm = 10000, z_scores = TRUE) %>%
  t()

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 't': requires numeric/complex matrix/vector arguments
```

If I change it to top=10000 I do not get any obvious error. I am following the dataset from the tutorial so I wonder what could have gone wrong. 

Hope you can help.

**Comment by adugourd** [comment]
You are very welcome :)

It is possible that with only top 100 responsive genes there may be no overlap at all with your input data. How many genes do you have in your ttop ?

**Comment by asumann** [comment]
11k genes in total. 
567 genes if abs(logFC)>0.6
5 genes if abs(logFC)>0.6 & adj.P.val <0.05

Many thanks!

**Comment by adugourd** [comment]
Hi,

ok :) 

you should not filter the ttop when using dorothea or progeny. All the genes are needed to build the background distribution to normalise the scores.

If you use the 11k genes as input there should be no problem.

**Comment by asumann** [comment]
Thank you! Yet, you filter in the tutorial(I am using the same dataset in the tutorial). This is also how I got to use top=100. Am I misinterpreting something in the tutorial?

**Comment by adugourd** [comment]
Hello,
sorry for the delayed answer. the paramter top=100 is for the progeny is to instruct progeny to use only the top 100 genes of its pathway signatures. But you need to provide all your genes as input, so that progeny can select them.
