### ISSUE TITLE
Missing input file for part 6

### ISSUE THREAD

**Issue by szsctt** [saezlab/transcriptutorial#23]
I'm going through the tutorial, and am up to part 6 - analysis of CARNIVAL results.  In the first chunk of this part, the results from the previous part are loaded, including a file `../results/carnival_sample_resolution.rds`.  This file is present in this repository, but isn't saved in any of the previous parts of the tutorial.  I'm unsure what this file contains - is it results that are specific to the dataset being analysed?  I'm tryinig to use my own data, but I'm not sure if I should use the version of this file that is in this repository, or if I should generate it for my own data.  Could you please advise if the file in this repository is general (can be used for any dataset), or if not, how to generate this file for my data?

**Comment by ulrmu** [comment]
I'd also like to know this! Especially how to create the file using my own data.
Can anyone comment?

**Comment by rosherbal** [comment]
Hi all,
Thanks for your comment and sorry for the delay on the response.
The file `carnival_sample_resolution.rds` is the result of running the series of scripts `sample_resolution_X.R`.
It is basically the same, but in this case we run the transcriptutorial for several samples. That is, we get PROGENy, DOROTHEA and CARNIVAL using directly the expression instead of the contrasts.  It is done this way to get more than one network, so we can do some network comparisons.

**Comment by ulrmu** [comment]
@rosherbal Thank you!
When I run the `sample_resolution_carnival.R` script, the following error is raised when trying to execute `runCARNIVAL`:
```
Error in checkWeights(weights, nodesPriorKnowledgeNetwork) : 
  Please provide a valid weights object: a vector with identifiers and their values. Or did you use carnivalOptions in place of weights object?
```

When I comment out `weightObj` as an input, the `runCARNIVAL` command executes. Is there any explanation why that happens or how it can be solved?

**Comment by ziweihf** [comment]
> @rosherbal Thank you! When I run the `sample_resolution_carnival.R` script, the following error is raised when trying to execute `runCARNIVAL`:
> 
> ```
> Error in checkWeights(weights, nodesPriorKnowledgeNetwork) : 
>   Please provide a valid weights object: a vector with identifiers and their values. Or did you use carnivalOptions in place of weights object?
> ```
> 
> When I comment out `weightObj` as an input, the `runCARNIVAL` command executes. Is there any explanation why that happens or how it can be solved?

Did you follow by this tutorial ？https://github.com/saezlab/transcriptutorial/blob/master/scripts/05_network_reconstruction_with_CARNIVAL.md 
 
carnival_result = runCARNIVAL( inputObj= iniciators,
                               measObj = tfList$t, 
                               netObj = sif, 
                               weightObj = progenylist$score, 
                               solverPath = "/Applications/CPLEX_Studio128/cplex/bin/x86-64_osx/cplex",
                               #solverPath = "/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/cplex", 
                               solver = "cplex",
                               timelimit=60,
                               mipGAP=0,
                               poolrelGAP=0 )


if so, you can try to check the type of progenylist$score (it's a data.frame ).  I got the same error. It worked after I changed it into vector
