### ISSUE TITLE
Batch correction

### ISSUE THREAD

**Issue by ulrmu** [saezlab/transcriptutorial#24]
Oh hai, Thank you for developing this pipeline!
I wonder, do you have any suggestions on how to handle/preprocess data from different batches upstream of the differential analysis?
Cheers!

**Comment by adugourd** [comment]
Hi, it depends on the type of data, but usually tools such as VSN are pretty flexible for normalisation of your data, and the removeBatchEffect function of limma is quite simple and efficient to remove batc heffect. You may wanny try "combat" as well for your batch effect, if your data doesn't have missing values.

**Comment by ulrmu** [comment]
Thank you for your quick reply! Does this mean you can replace the normalization method that you use in part 1 by any normalization method that does batch correction? For example, can you use either of the methods you propose as an input to runLimma in part 2?

**Comment by ulrmu** [comment]
Alternatively, it seems that runLimma can accept a regress_out argument which calls removeBatchEffect. Using this strategy, batch correction would occur after normalization in part 1. Could you comment if this would be an acceptable approach? :)

**Comment by adugourd** [comment]
regress_out is still kind of an experimental feature. I would not advise to use it at the moment :) I haven't taken the time to complete it yet.

I would say that yes, any normalisation and batch effect correction is acceptable, at the users discretion :) There is many possible solutions for that question.

**Comment by ulrmu** [comment]
Thanks for the advise :) 
I will do the batch correction in an upstream step.
Thanks again!
