### ISSUE TITLE
carnival_visNet visualization in part 05

### ISSUE THREAD

**Issue by ulrmu** [saezlab/transcriptutorial#29]
Hi there,

Visualizing the network in the last part of part 05 using `carnival_visNet `produces a a network where all nodes are aligned into one straight line. Using the html file in a browser, the nodes cannot be disentangled. 

Is anyone else experiencing this issue? 
Is there any way to use the html file in a network visualization program similar to Cytoscape?

Thank you for any advice!

**Comment by adugourd** [comment]
Hi,

I'm not sure why this bug occur tbh, this has to do with the visnetwork package I assume.

If you want you can indeed visualise the network in cytoscape as well, all you need to do is to write carnival_result$weightedSIF and carnival_result$nodesAttributes tables in csv files and import them in cytoscape :)

Cheers

Aurelien

**Comment by ulrmu** [comment]
Thank you, @adugourd !
Could you explain how to properly import/use the two files to visualize the data?

**Comment by adugourd** [comment]
You can use the write_csv function in R to export the carnival_result$weightedSIF and carnival_result$nodesAttributes tables

The you can check this video to learn how to import csv files in cytoscape :)

https://www.youtube.com/watch?v=Z8jUmJL2HFw

Cheers,

Aurelien

**Comment by CheyennedeVriend** [comment]
Hi,

I'm having the same exact problem. I did watch the youtube tutorial but I do not understand how to combine these files into cytoscape. Could you please explain how to use the WeightedSIF and NodeAttribute tables into cytoscape?

Thanks in advance!

Kind regards,
Cheyenne
