### ISSUE TITLE
Unable to call runCarnival

### ISSUE THREAD

**Issue by CheyennedeVriend** [saezlab/transcriptutorial#39]
Hi,

I've been really enjoying the tutorials from saez lab and I have learned a lot of them. At this point I'm at "05_network_reconstruction_with_CARNIVAL". However I have encountered an error while calling the following command line:

`carnival_result = runCARNIVAL( inputObj= iniciators,
                               measObj = tfList$t, 
                               netObj = sif, 
                               weightObj = progenylist$score, 
                               solverPath = "/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/cplex", 
                               solver = "cplex",
                               timelimit=7200,
                               mipGAP=0,
                               poolrelGAP=0 )`

`Error in checkWeights(weights, nodesPriorKnowledgeNetwork) : 
Please provide a valid weights object: a vector with identifiers and their values. Or did you use carnivalOptions in place of weights object?

5.
stop(paste(nullObjectError, incorrectOrderError))
4.
checkWeights(weights, nodesPriorKnowledgeNetwork)
3.
checkData(perturbations, measurements, priorKnowledgeNetwork, 
weights)
2.
runVanillaCarnival(perturbations = inputObj, measurements = measObj, 
priorKnowledgeNetwork = netObj, weights = weightObj, carnivalOptions = opts)
1.
runCARNIVAL(inputObj = iniciators, measObj = tfList$t, netObj = sif, 
weightObj = progenylist$score, solverPath = "/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/cplex", 
solver = "cplex", timelimit = 7200, mipGAP = 0, poolrelGAP = 0)`

How I understood this, I may have a problem with my WeightObj, which looks like this:
![image](https://user-images.githubusercontent.com/74907397/166950697-f823fd07-c3f3-43f0-b799-8aaa9299df3b.png)

I hope you can help me, because I'd really like to start analyzing with my own data as well. 

Thanks in advance!

Kind regards,
Cheyenne

I

**Comment by gabora** [comment]
Hi @CheyennedeVriend 
thanks for writing! This issue sounds familiar to me. 
could you please check your CARNIVAL version? You could do that by running `sessionInfo()` and checking the output.  It should be 2.6.0.
If it is 2.5.0 or earlier, then please update the CARNIVAL from Bioconductor or from our github: "saezlab/CARNIVAL". 
Let me know if this was the issue. 

best,
Attila

**Comment by CheyennedeVriend** [comment]
Hi, Thanks for the quick reply!

I have updated my Rversion as well as all my packages (including CARNIVAL). I now have the correct version running but I've encountered another error:

`load(file = system.file("progenyMembers.RData",package="CARNIVAL"))`

Gives the following error message:
`Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
2. readChar(con, 5L, useBytes = TRUE)
1. load(file = system.file("progenyMembers.RData", package = "CARNIVAL"))`

I still proceeded as I expected this to still be loaded into my environment. After running the following:

`# run carnival
carnival_result = runCARNIVAL( inputObj= iniciators,
                               measObj = tfList$t, 
                               netObj = sif, 
                               weightObj = progenylist$score, 
                               solverPath = "/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/cplex", 
                               solver = "cplex",
                               timelimit=7200,
                               mipGAP=0,
                               poolrelGAP=0 )`

I got the following error:

`Error in checkCarnivalOptions(carnivalOptions) : 
Incorrect parameters setup 
Error in solverPath: Invalid path to solver provided.
4. stop("Incorrect parameters setup \n", paste(collectedMessages, 
collapse = "\n"))
3. checkCarnivalOptions(carnivalOptions)
2. runVanillaCarnival(perturbations = inputObj, measurements = measObj, 
priorKnowledgeNetwork = netObj, weights = weightObj, carnivalOptions = opts)
1. runCARNIVAL(inputObj = iniciators, measObj = tfList$t, netObj = sif, 
weightObj = progenylist$score, solverPath = "/Applications/CPLEX_Studio129/cplex/bin/x86-64_osx/cplex", 
solver = "cplex", timelimit = 7200, mipGAP = 0, poolrelGAP = 0)`

Thanks again!

Kind regards,
Cheyenne

**Comment by CheyennedeVriend** [comment]
Thanks that fixed it!

I now still have the problem with the cplex application that I need to use as 'solver' in the code. 

I couldn't find the application folder within the transcriptorial. Therefore, I downloaded and unzipped the R interface to cplex "https://cran.r-project.org/web/packages/Rcplex/index.html" via this link. 

I had too many problems with downloading cplex so I decided to download lpsolver via the link provided in the CARNIVAL page (https://github.com/saezlab/CARNIVAL). 

Then I put the following command into Rstudio:
`carnival_result = runCARNIVAL( inputObj= iniciators,
                               measObj = tfList$t, 
                               netObj = sif, 
                               weightObj = progenylist$score, 
                               solverPath = "C:/Users/cheye/AppData/Local/Temp/RtmpW691DA/downloaded_packages", 
                               solver = "lpSolve",
                               timelimit=7200,
                               mipGAP=0,
                               poolrelGAP=0 )`

Then I received a large message with one main error:
--- Start of the CARNIVAL pipeline ---
14:52:41 06.05.2022 Carnival flavour: vanilla
Warning in preprocessPriorKnowledgeNetwork(priorKnowledgeNetwork) :
  self loop(s) detected and removed from prior knowledge network.
Warning in checkPerturbations(perturbations, nodesPriorKnowledgeNetwork) :
  These perturbation nodes are provided as NA, their activity will be inferred: MDFI | HOMER1 | ITPR3 | ASPH | RNF24 | CABP1 | SESTD1 | MX1 | NPHS2 | SNF8 | CNR1 | PIRT | MAP7 | PACSIN3 | BSPRY | CALB1 | KL | RAB11A | S100A10 | PDZD3 | NIPSNAP1 | NYX | EFHC1 | PTPN13 | PRKCSH | ESPN | ZIC1 | TUB | CDC73 | SYMPK | MYCN | KLF2 | NPAS2 | ATAD2 | BACE2 | PREX2 | PTPRD | RPL11 | SPNS1 | ATG4B | ADGRV1 | RALB | PRKACG | PKNOX1 | ATG101 | MIB1 | HRK | UBE2T | KDM2B | IL22 | CXCL16 | CCL3L1 | ASF1B | NMI | CARD18 | ISG15 | CARD16 | ANO9 | KLF6 | FLT3LG | KITLG | SERPINB9 | APLF | E2F7 | TLX1 | PLK3 | GTF3C4 | KDM3B | KDM3A | KDM4B | KDM4A | APIP | CAPNS1 | XRCC5 | KMT2B | PRMT6 | SETD1A | CXCL9 | CCL8 | CCL4 | SETDB2 | KMT2E | RIOX1 | SETD7 | PRDM2 | DOT1L | ATG4A | VMP1 | SUPT20H | RAB33B | CISD2 | UBE2M | OS9 | SSBP1 | RORB | NR1D2 | CAND1 | GLRX | SIRT6 | NKRF | FRAT2 | MIR22HG | CDK11A | SMARCB1 | NSMCE2 | TRIM8 | RECQL5 | MARCHF5 | DTX3L | NFKBIZ | ASH1L | TNFSF14 | CD40LG | TNFSF13B | LTA  [... truncated]
Warning in checkMeasurements(measurements, nodesPriorKnowledgeNetwork) :
  These measurement nodes are not in prior knowledge network and will be ignored: DUX4 | SIX2 | SNAI2 | SNAPC4 | THAP11 | ZNF263
Warning in checkWeights(weights, nodesPriorKnowledgeNetwork) :
  These nodes are not in prior knowledge network and will be ignored: P53
14:52:41 06.05.2022 Generating variables for lp problem
14:52:41 06.05.2022 Done: generating variables for lp problem
Saving preprocessed data.
Done: saving parsed data: ./parsedData_t14_52_41d06_05_2022n38.RData
14:52:41 06.05.2022 Generating formulation for LP problem
14:52:59 06.05.2022 Done: generating formulation for LP problem.
Saving LP file
Done: Saving LP file: ./lpFile_t14_52_41d06_05_2022n38.lp
14:53:04 06.05.2022 Solving LP problem
Parsing .lp file for lpSolve
Rows: 297661 Columns: 1
── Column specification ────────────────────────────────────────────────
Delimiter: ","
chr (1): X1

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error: cannot allocate vector of size 85.5 Gb

I hope you can help me fix this issue, thanks again!

Kind regards,
Cheyenne

**Comment by gabora** [comment]
- I think your error is related to the use of lpSolve. 
- LPsolve is an R package and it is automatically installed with CARNIVAL. However, it can solve networks up to, let's say, 100 edges (very, very limited). Therefore we use it for very small illustrative examples and for testing toy examples. 
- we would strongly recommend to download either CPLEX or Gurobi. Both of them are commercial softwares with free license for academia. 
- if you dont have academic affiliation then you can give a try to CBC. It is something between CPLEX and LPSolve. (check links here: https://github.com/saezlab/CARNIVAL#prerequisites) 
- we are working on a different formulation of CARNIVAL with some heuristics, that would make CBC a possible alternative of CPLEX and Gurobi, but this feature is in development. I would say we need at least a month for it. 
-

**Comment by gabora** [comment]
Hi @CheyennedeVriend 

Please note the following line in your report: 

> CPLEX> CPLEX Error 1016: Community Edition. Problem size limits exceeded. Purchase at http://ibm.biz/error1016.

The Academic version of CPLEX (that I mentioned above) is not the same as the Community edition. 
The Community edition is limited to 1000 optimization variables, while there is not such limit for the Academic version.
 
To obtain an academic license, please follow the link: https://www.ibm.com/academic/home

best,
Attila
