### ISSUE TITLE
Transcriptorial 6: Enrichment analysis p-value errors

### ISSUE THREAD

**Issue by CheyennedeVriend** [saezlab/transcriptutorial#41]
Hi again,

I really appreciated your help last time with the installment of CPLEX. Therefore, I have finally been able to finish tutorial 5. At this point i'm trying to finish tutorial 6, however I suspect a possible error but I do not know where to look I hope you can help me.

I literally copied the following commands from the tutorial and I am using the available data.

`# Load pathways
pathways = gmt_to_csv("C:/Users/cheye/OneDrive/Bureaublad/Radboud/Master 21-22/Internship/Data and analysis/Tutorial_Saez_lab/Full tutorial/data/c2.cp.v7.1.symbols.gmt")

# Extract nodes and background
nodes_carnival = extractCARNIVALnodes(carnival_result)

# Run GSA hyper Geometric test
sig_pathways <- runGSAhyper(genes = nodes_carnival$sucesses, 
    universe = nodes_carnival$bg, gsc = loadGSC(pathways))
sig_pathways_df <- as.data.frame(sig_pathways$resTab)  %>% 
  tibble::rownames_to_column(var = "pathway") 

#data for plotting
PathwaysSelect <- sig_pathways_df %>%
    dplyr::select(pathway, `p-value`, `Adjusted p-value`) %>%
    #dplyr::filter(`Adjusted p-value` <= 0.001) %>%
    dplyr::rename(pvalue = `p-value`, AdjPvalu = `Adjusted p-value`) %>% 
    dplyr::mutate(pathway = as.factor(pathway))

PathwaysSelect <- data.frame(t(apply(PathwaysSelect, 1, function(r){
  aux = unlist(strsplit( sub("_",";", r["pathway"]), ";" ))
  r["pathway"] = gsub("_", " ", aux[2])
  return(c(r, "source" = aux[1]))
})))

colnames(PathwaysSelect) = c("pathway", "pvalue", "AdjPvalu", "source")
PathwaysSelect$AdjPvalu = as.numeric(PathwaysSelect$AdjPvalu)

ggdata = PathwaysSelect %>% 
   # dplyr::filter(AdjPvalu <= 0.05) %>% 
    dplyr::group_by(source) %>% 
    dplyr::arrange(AdjPvalu) %>%
    dplyr::slice(1:5)

  
# Visualize top results
ggplot(ggdata, aes(y = reorder(pathway, AdjPvalu), x = -log10(AdjPvalu)), color = source) + 
        geom_bar(stat = "identity") +
        facet_grid(source ~ ., scales="free_y") +
        scale_x_continuous(
                         expand = c(0.01, 0.01),
                         limits = c(0, ceiling(max(-log10(PathwaysSelect$AdjPvalu)))),
                         breaks = seq(floor(min(-log10(PathwaysSelect$AdjPvalu))), ceiling(max(-log10(PathwaysSelect$AdjPvalu))), 1),
                         labels = math_format(10^-.x)
                         ) +
        annotation_logticks(sides = "bt") +
        theme_bw() +
        theme(axis.title = element_text(face = "bold", size = 12),
              axis.text.y = element_text(size = 6)) +
        ylab("")
`

However, an error occurs due to the fact that non of the p-values are below 1. When I remove these filtering steps I get the following PathwaysSelect df

![image](https://user-images.githubusercontent.com/74907397/170488019-3ceb2ce8-1eaa-4605-8a23-50fe259de63f.png)

Do you have an idea why all the p-values are set to one? How can I solve this? I'd really like to finish the tutorials so I can start using CARNIVAL on my own data.

Thanks in advance!

Kind regards,
Cheyenne

**Comment by adugourd** [comment]
Hi Cheyenne,

Apologies for the delayed answer. Unfortunately i'm not able to reproduce the error. When I clone the repository fresh and run the markdown I get a dataframe that looks normal:
![Screenshot 2022-06-02 at 09 43 30](https://user-images.githubusercontent.com/16302934/171579932-1fe24849-53c8-4693-b9d9-e06de99ac04c.png)

Regardless, this part of the tutorial isn'T the most important. As long as you are able to obtain a Carnival network, you can start exploring it. The over-representation analysis is simply one example of how to do so.

Cheers,

Aurelien

**Comment by CheyennedeVriend** [comment]
Hi Aurelien,

Thankyou for you answer. I will try to run it again. I managed to produce Carnival networks for both the tutorial and my own data, so I think I will manage for now.

Thanks again!

Kind regards,
Cheyenne
