### ISSUE TITLE
04_TranscriptionFactor_activity_with_Dorothea error in R script

### ISSUE THREAD

**Issue by dilipgosar** [saezlab/transcriptutorial#42]
Dear Sir/Madam,

I am trying tutorial on Dorothea I am getting following error. I like to know if you can help me.

volcano_nice(as.data.frame(ttop_KOvsWT[ttop_KOvsWT$ID %in% targets_IRF2,]), 
+              FCIndex = 2, pValIndex = 5, IDIndex = 1, nlabels = 20, label = TRUE, 
+              straight = FALSE)
Error in abs(df[, FCIndex]) : 
  non-numeric argument to mathematical function

Appreciate your help.

Sincerely,

Dilip Gosar

**Comment by adugourd** [comment]
Hi Gosar,

Can you show what as.data.frame(ttop_KOvsWT[ttop_KOvsWT$ID %in% targets_IRF2,]) looks like ?

Cheers,

Aurelien
