### ISSUE TITLE
Comparing Cancer cell lines with normal tissues

### ISSUE THREAD

**Issue by RzgarHosseini** [saezlab/transcriptutorial#43]
Hi all,

I think in some part of the pipeline (e.g. DORothEA based TF-activity inference step), a differential gene-expression analysis has been performed. 
My question is that how cancer cell lines have been compared against normal tissues? Do you usually use TCGA match-normal for this purpose? or GTEX expression profiles of normal tissues? (e.g. https://ucsc-xena.gitbook.io/project/how-do-i/tumor-vs-normal)
I guess you usually use Limma for differential gene expression analysis. Am I right?
I assume that you have obtained the RNA-Seq profiles of the cancer cell lines from CellModelPassport?

Many thanks for your response in advance

Best,
SRH

**Comment by RzgarHosseini** [comment]
Don't worry, be happy

**Comment by adugourd** [comment]
HI, sorry for the delay.

the data in the tutorial comes from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE119931

We use limma for differential analysis, comparing WT and KO.

Cheers,

Aurelien
