### ISSUE TITLE
Got a problem using assignPROGENYScores

### ISSUE THREAD

**Issue by Holmes815** [saezlab/transcriptutorial#45]
Hi, i´m using CARNIVAL to infer the network of reuglation in my scRNAseq data, i obtained my progeny results following this tutorial: https://saezlab.github.io/progeny/articles/ProgenySingleCell.html

The dataframe that i use is basically a dataframe with the pathways and scores inferred by progeny after using the prevously mentioned tutorial (just like the csv that is used in the chapter 05 of transcriptutorial) but this error keeps poping:

Error in progenyMembers[[which(names(progenyMembers) == pathways[ii])]] : 
  attempt to select less than one element in get1index

I dont know what else to do, thanks in advance for the attention.

**Comment by adugourd** [comment]
Hi, 

you can try to chek what are the pathway names in pathways[ii] if they match the names of the progeny members you get with names(progenyMembers) 

However, we haven't tested carnival with single cell data yet, the tool was really intended for such a setting. I would at least avoid using progeny pathway to run carnival from single cell.
