### ISSUE TITLE
Progeny documentation and tutorial script conflict

### ISSUE THREAD

**Issue by IvanEllson** [saezlab/transcriptutorial#9]
Hello, regarding the input of R Progeny function: documentation indicates that you have to enter an expr object (HGNC/MGI symbols in rows and samples in columns) as the main input, but this tutorial uses the t statistic obtained from limma differential expression. This looks like it forces you to do the differential expression analysis with limma. Please explain this in the tutorial or change the documentation. Thank you

**Comment by adugourd** [comment]
Thanks for your input. I'm not sure I fully understand your comment, the tutorial actually shows how progeny can be used both with the expression object or the resulting t-statistics of a differential analysis. Both examples are present in the tutorial.

**Comment by IvanEllson** [comment]
Hello, thank you for your answer. Allow me to explain:
If you access the Progeny documentation (help("progeny") in an R console), it says that you must enter an expression object as input. But it doesn´t tell you that you can also use the resulting t-statistics of a differential analsis, as you do in this tutorial.
The same thing happens with Dorothea's viper function.
This conflict is especially relevant in the current tutorial, because you use the t-statistics in Progeny and Dorothea to later compute the Carnival network.
I hope it helps.
Thank you

**Comment by adugourd** [comment]
Ah I see, Thanks for noticing this. We will update the package documentations :)
